version: "3.8"
services:
  db:
    image: mysql:8.3
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: demo_password
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
